<?php

namespace Tests\Unit;

use App\Media\Storage\Storage;
use App\Models\Settings;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Tests\TestCase;

class StorageTest extends TestCase
{
    use RefreshDatabase;

    protected bool $seed = true;

    private Storage $storage;

    private string $firstuuid;

    private string $seconduuid;

    private \VirtualFileSystem\FileSystem $vfs;

    private function baseVfs(): \VirtualFileSystem\FileSystem
    {
        $vfs = new \VirtualFileSystem\FileSystem;
        $vfs->createDirectory('/storage1/testfolder', true);
        $vfs->createDirectory('/storage2');
        $vfs->createFile('/storage1/testfolder/test.txt', 'test folder for normal handling');
        $vfs->createFile('/storage2/test2.txt', '');

        // create some files for the tests
        $zip = new \PhpZip\ZipFile;
        $zip->addFromString('test.txt', 'testing text');

        $vfs->createFile('/storage1/test.zip', $zip->outputAsString());

        return $vfs;
    }

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->vfs = $this->baseVfs();

        // add some default settings to the database for these tests
        $this->firstuuid = Settings::addScannerDir([
            'driver' => 'local',
            'root' => $this->vfs->path('storage1'),
        ]);

        $this->seconduuid = Settings::addScannerDir([
            'driver' => 'local',
            'root' => $this->vfs->path('storage2'),
        ]);

        $this->storage = $this->app->make(Storage::class);
    }

    /**
     * A basic unit test example.
     */
    public function test_storage_drivers(): void
    {
        $firstfile = $this->firstuuid.'://testfolder/test.txt';
        $secondfile = $this->seconduuid.'://test2.txt';

        $this->assertNotNull($this->storage->storage($firstfile));
        $this->assertNotNull($this->storage->storage($secondfile));
        $this->assertNotNull($this->storage->storage($this->firstuuid));
        $this->assertNotNull($this->storage->storage($this->seconduuid));
    }

    public function test_storage_protocol(): void
    {
        $this->expectException(\InvalidArgumentException::class);

        $this->storage->storage('google.es');
    }

    public function test_storage_path_parsing(): void
    {
        $path = Storage::path('protocol://path/to/file');

        $this->assertEquals('protocol', $path->disk);
        $this->assertEquals('path/to/file', $path->path);
        $this->assertEquals('', $path->container);
        $this->assertEquals('protocol://path/to/file', (string) $path);

        $path = Storage::path('protocol://path/to/file.zip:file/contents.jpg');

        $this->assertEquals('protocol', $path->disk);
        $this->assertEquals('path/to/file.zip', $path->container);
        $this->assertEquals('file/contents.jpg', $path->path);
        $this->assertEquals('protocol://path/to/file.zip:file/contents.jpg', (string) $path);

        $path = Storage::path('protocol://path/to/file.zip:file/contents?.jpg');

        $this->assertEquals('protocol', $path->disk);
        $this->assertEquals('path/to/file.zip', $path->container);
        $this->assertEquals('file/contents?.jpg', $path->path);
        $this->assertEquals('protocol://path/to/file.zip:file/contents?.jpg', (string) $path);

        $path = Storage::path('protocol://file.zip:file/contents?.jpg');

        $this->assertEquals('protocol', $path->disk);
        $this->assertEquals('file.zip', $path->container);
        $this->assertEquals('file/contents?.jpg', $path->path);
        $this->assertEquals('protocol://file.zip:file/contents?.jpg', (string) $path);

        $this->expectException(\InvalidArgumentException::class);
        Storage::path('malformed:path');
    }

    public function test_storage_path_parsing_extra(): void
    {
        $this->expectException(\InvalidArgumentException::class);
        Storage::path('malformed://path:multiple:containers');
    }

    public function test_handlers(): void
    {
        $this->storage->open($this->firstuuid.'://testfolder/test.txt', function ($stream): void {
            $this->assertIsResource($stream);

            $this->assertEquals('test folder for normal handling', stream_get_contents($stream));
        });

        $this->storage->open($this->firstuuid.'://test.zip:test.txt', function ($stream): void {
            $this->assertIsResource($stream);

            $this->assertEquals('testing text', stream_get_contents($stream));
        });
    }
}
