on: push
name: CI
jobs:
  phpunit:
    runs-on: ubuntu-latest
    container:
      image: kirschbaumdevelopment/laravel-test-runner:8.3

    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1

    - name: Install composer dependencies and make
      run: |
        git config --system --add safe.directory '*'
        touch database/database.sqlite
        apt install -y make
        composer install
        make dev_db_fresh
        make ide_helper

    - name: Prepare Laravel Application
      run: |
        cp .env.ci .env
        php artisan key:generate
        php artisan jwt:secret --force --no-interaction

    - name: Run linter
      run: make lint

    - name: Run Testsuite
      run: vendor/bin/phpunit --coverage-clover coverage/clover.xml

    - name: Code Coverage Summary Report
      uses: saschanowak/CloverCodeCoverageSummary@1.1.0
      with:
        filename: coverage/clover.xml

    - name: 'Add Code Coverage to Job Summary'
      run: |
        cat code-coverage-summary.md >> $GITHUB_STEP_SUMMARY
        cat code-coverage-details.md >> $GITHUB_STEP_SUMMARY
